name: Hasan Basri
markdown: redcarpet
fullpath: http://creatorb.github.io
description: Personal Website
baseurl: 
permalink: /blog/:categories/:title.html
title: creatorb
paginate: 10
highlighter: null

# More
author:
    fullname	: Hasan Basri
    codename	: creatorb
    twitter		: creatorbe
    github 		: CreatorB
    facebook: creatorbe
    google: CreatorB doodler
    gplusid: 118116077271759320582

googleverify: gC8gMLC1UpPDYi2y5KR_9Sq79n4TYMiQM7UcSvtyfms
disqusid: avi-aryan-github
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']