# Site settings
title: Hasan Basri
subtitle: "Fullstack Developer"
email: creatorb45@gmail.com
description: "creatorb fullstack developer"
baseurl: ""
url: ""
twitter_username: "creatorbe"
github_username:  "CreatorB"

# Build settings
markdown: kramdown
permalink: pretty

#paginator
paginate: 5
paginate_path: "/page:num/"

# Sass
sass:
    style: :compressed