# Site settings
title: Hasan Basri
subtitle: "creatorbe - Indonesian Programmer"
email: creatorb45@gmail.com
description: "creatorb's portfolio page - a place where i'm push some of my development projects"
baseurl: ""
url: ""
twitter_username: "creatorbe"
github_username:  "CreatorB"

# Build settings
markdown: kramdown
permalink: pretty

#paginator
paginate: 5
paginate_path: "/page:num/"

# Sass
sass:
    style: :compressed